### ISSUE TITLE
English Audio with polish subs

### ISSUE THREAD

**Issue by SzarikwSzaliku** [Murzinio/AndromedaLanguagePatcher#1]
Is it possible to play with english audio and polish subs? The option for english audio disappears when i change files. Only french and deutsch remain.

**Comment by Murzinio** [comment]
Have you downloaded pl subs? Forgot to upload them for new version, I will add them in a minute. Meanhwile you can download them here: 
http://bsn.boards.net/thread/5113/playing-russian-polish-versions-english?page=1

If it still won't work, try this exe and let me know if it's fixed:
http://www100.zippyshare.com/v/2BP1lyWb/file.html

**Comment by SzarikwSzaliku** [comment]
I'm already using that .exe but there's only french and deutsch audio. I'm playing on french audio and pl subs, but i want to use english audio if it possible.

**Comment by Murzinio** [comment]
I'm not sure why it happens, seems to work ok on english audio + polish subs for other people. Have you tried other solutions before and modified your files? If yes, try to verify game files and use the progam after that. If it still won't work, check what is the value of Locale in HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\BioWare\Mass Effect Andromeda. If it's something else than en_US or pl_PL than probably modifiying the exe in different way is needed.

**Comment by SzarikwSzaliku** [comment]
In registry is pl_PL value. I tried verify game files few times. It's strange if it works for other people. https://gyazo.com/5611c19fede20ba09127fad0df771b32 After using ur program there's french menu (same as a guy in forum) and two settings for audio: french and deutsch. I tried manually change .exe, use ur .exe and ur programme. Maybe i should just give up and learn some french :p

**Comment by Murzinio** [comment]
Try this exe:
https://mega.nz/#!OR5F0Yga!pe-YTnxz2ZH0Aj2GyKBYsW_TSyjGBHjjWxLQTgfvyBc
Theoretically French should change to English.

**Comment by ukakiki** [comment]
Have the same problem. Patch change exe. First there was french sub, change it to polish, but audio is german only. please help!

**Comment by Murzinio** [comment]
Try this https://mega.nz/#!rEx0HLTL!lA7Ec824p0UQ77y2S1CMZY4PDBVGs_BFxyYQo7BzY_Q

**Comment by ukakiki** [comment]
Didn't work. No pl sub and none audio to choose in options.

**Comment by Murzinio** [comment]
Where do you live?

**Comment by ukakiki** [comment]
Poland, and have global version

**Comment by Murzinio** [comment]
Check the size in bytes of Data\Win32\loc\en.sb and en.toc files and post it here.

**Comment by ukakiki** [comment]
en.sb - 1KB
en.tov - 114KB
there are also:
de.sb - 1KB
de.toc - 113KB

**Comment by Murzinio** [comment]
Send me en.toc file if it's not a problem, also you can try changing your Origin language, changing the language in the registry, I doubt it will work but worth a try. If all else fails, theoretically I could write a script to compare all the files, and maybe I will figure out something looking at the differences between region locked and global versions.

**Comment by ukakiki** [comment]
https://drive.google.com/file/d/0B-FWDvandz-yVzVsSWpJUGlFNWc/view?usp=sharing

**Comment by ukakiki** [comment]
in registry change to pl_PL??

**Comment by Murzinio** [comment]
Yes.

**Comment by Murzinio** [comment]
Files are identical so that's not a problem... If registry editing won't help, try deleting other files from Data/Win32/loc and Patch/Win32/loc. Leave only en.sb and en.toc.

**Comment by ukakiki** [comment]
Ok that helped! audio is english (but it's written "german"). thanks a lot! :)

**Comment by Murzinio** [comment]
What helped? Deleting the files or registry editing? Would be good to know in case someone else has this problem in the future. Also which exe are you using right now?

**Comment by ukakiki** [comment]
Deleting files

**Comment by ukakiki** [comment]
And I used your patcher 1.11 (en_US to pl)

**Comment by Murzinio** [comment]
Ok, great. I will add this to the readme.
