### ISSUE TITLE
not compatible with version of windows

### ISSUE THREAD

**Issue by ericmeln** [Murzinio/AndromedaLanguagePatcher#3]
Before I use this I can open the game with the wrong language. After using the patch the new exe won't open, gives the error "the version of this file is not compatible with the version of windows you're running".

**Comment by Murzinio** [comment]
Repair the game and try again, run the program with admin priviliges. If it still won't work, What's your game version? Which patch? Could you send me the edited exe?

**Comment by ericmeln** [comment]
Wow. I could have sworn I ran with admin control before. Last time I didn't pick an original language, so maybe it was that, or I was picking en_UK. But I ran with admin, picked russian original and english_US and it worked. Thanks.

**Comment by Murzinio** [comment]
Btw, if you updated your game to 1.05, you should update localization files, I uploaded updated version right now and added links to the readme.
