### ISSUE TITLE
Patch 1.06

### ISSUE THREAD

**Issue by Infixo** [Murzinio/AndromedaLanguagePatcher#4]
Unfortunately there's a new patch 1.06 and the patcher is no longer working :(

**Comment by Trupacz** [comment]
I think it's problem with loctext files so i would be glad if someone could upload and link them from version 1..06

**Comment by Murzinio** [comment]
Most likely only new localization files are needed like in the last patch. So if anyone could upload them it would be great. I don't have the game on my PC anymore so I would need all language files.

**Comment by Trupacz** [comment]
[localization.zip](https://github.com/Murzinio/AndromedaLanguagePatcher/files/992423/localization.zip)
Here take my polish loctext files

**Comment by Murzinio** [comment]
Thx. When I get global files I'll update it.

**Comment by Murzinio** [comment]
I uploaded the files. Let me know if it works.

**Comment by Norfice** [comment]
Trupacz i send you massage in Origin. Pleas accept me :)
Murzinio all hope in you. You have been chosenone :) ( Możemy to w czasie rzeczywistym potestować jeśli ci się nie chce instalować andromedy mój nick Norfice avatar smoka)

**Comment by bkradek0** [comment]
Witam wszystkich. Ja po aktualizacji 1.06 MEA EU użyłem patch v 1.00 i mam napisy pl. Gra działa, oryginalne pliki loctext.

**Comment by Norfice** [comment]
Potwierdzam wszystko działa w nowej wersji 106 od Murzinio :) Właśnie odpaliłem i śmiga aż miło dla PL :) 
Wybraniec spisał się na medal

**Comment by alexeibs** [comment]
Murzinio, does new patcher work with russian ME? I can upload russian loctext files if you need them.

**Comment by Murzinio** [comment]
Should work with russian too. Files are in the pack.

**Comment by alexeibs** [comment]
Thank you

**Comment by Trupacz** [comment]
I will support your little project in the future with my PL files.

**Comment by Murzinio** [comment]
Ok, when a new patch comes out and you don't see the updated files here, just create a new issue.
