### ISSUE TITLE
Patch 1.08

### ISSUE THREAD

**Issue by Murzinio** [Murzinio/AndromedaLanguagePatcher#5]
If anyone would like to upload the new language files, link them here please.

**Comment by Jurigag** [comment]
[loctext.zip](https://github.com/Murzinio/AndromedaLanguagePatcher/files/1063382/loctext.zip)
[loctext.zip](https://github.com/Murzinio/AndromedaLanguagePatcher/files/1063383/loctext.zip)

English files.

**Comment by Jurigag** [comment]
English files:
[loctext-english-patch-108.zip](https://github.com/Murzinio/AndromedaLanguagePatcher/files/1063387/loctext-english-patch-108.zip)
[loctext-data-english-108.zip](https://github.com/Murzinio/AndromedaLanguagePatcher/files/1063388/loctext-data-english-108.zip)

Though they have 01.06.2017 modification date.

**Comment by MateuszCzarnowski** [comment]
Everything works fine with files provided by @Jurigag .

PL->ENG conversion.

**Comment by Jurigag** [comment]
But we need polish one too, right?

**Comment by MateuszCzarnowski** [comment]
Here you go.

[loctext-polish-108.zip](https://github.com/Murzinio/AndromedaLanguagePatcher/files/1063494/loctext-polish-108.zip)

**Comment by Murzinio** [comment]
Thx. I'll update the links.

**Comment by Murzinio** [comment]
Ok, I still need russian files.

**Comment by Murzinio** [comment]
Got all the files now.
