### ISSUE TITLE
1.09 Patch

### ISSUE THREAD

**Issue by liamcos** [Murzinio/AndromedaLanguagePatcher#6]
Can anyone please share 1.09 update english language file?

**Comment by bkradek0** [comment]
[localisation_109.zip](https://github.com/Murzinio/AndromedaLanguagePatcher/files/1131593/localisation_109.zip)

**Comment by liamcos** [comment]
@bkradek0 
thanks！ finaly get the files,and it works!

**Comment by bkradek0** [comment]
These are the original game files.

**Comment by Grasher134** [comment]
I can confirm, that it doesn't work without files, provided by @bkradek0 

So we can add these files in the Readme.md and close the issue. @Murzinio

**Comment by Murzinio** [comment]
Thx for the files and testing, I will update the readme.
