### ISSUE TITLE
patch 1.10

### ISSUE THREAD

**Issue by ghost** [Murzinio/AndromedaLanguagePatcher#7]
I have the files for patch 1.10 localization, please test them if they work for you. They worked for me. 
https://files.fm/u/k3rfjzde#_   - the link to an archive with the files

**Comment by Trupacz** [comment]
Here are my polish files
[locfiles PL_pl.zip](https://github.com/Murzinio/AndromedaLanguagePatcher/files/1235751/locfiles.PL_pl.zip)

**Comment by Trupacz** [comment]
also akimichigordo could you reupload your files as .zip archive ?

**Comment by pablomag** [comment]
zip for 1.10 patch plz?

**Comment by Murzinio** [comment]
Let me know if it works and sorry for the delay. https://mega.nz/#!uJgFHbST!onLZ1vnMj7hC0NLYGV1XZP5BuEWR0zjtlSE9WKJr9yg

**Comment by pablomag** [comment]
It works perfectly, thank you!

**Comment by Murzinio** [comment]
Ok, added to readme.
